<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <PublishAot>true</PublishAot>
    <InvariantGlobalization>true</InvariantGlobalization>
    <RootNamespace>JevMcp</RootNamespace>
    <AssemblyName>JevMcp</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MCPSharp" Version="1.0.11" />
    <PackageReference Include="MessagePack" Version="2.5.305" />
    <PackageReference Include="Microsoft.AspNetCore.Server.Kestrel.Core" Version="2.3.13" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="10.0.12" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\TypeSafe.Client\TypeSafe.Client.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="appsettings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
